### PR TITLE
feat: auth page

### PR DESCRIPTION
**Pull request by partha8**
Hey everyone, i have added the auth page. Please have a look and give your reviews. Thank you!

### CODE REVIEW

**Review by vrinda-mahajan — APPROVED** [review]
LGTM

**Comment by hsnice16** [comment]
Everything looks good. But complete all the requirements mentioned in PRD, for the sign up page these things should be there
image

**Review by hsnice16 — APPROVED** [review]

**Comment by hsnice16** [comment]
I have approved, but add these requirements.

**Comment by partha8** [comment]
> I have approved, but add these requirements.

Added the requirements. Thank you @hsnice16 for pointing them out.

**Pull request merged**
