### PR TITLE
feat: added products listing page

### PR DESCRIPTION
**Pull request by partha8**

### CODE REVIEW

**Review by anik31 — COMMENTED** [review]
Suggestion - you can decrease the spacing on top of filter component

**Comment by partha8** [comment]
> Suggestion - you can decrease the spacing on top of filter component

yup, on it!

**Comment by partha8** [comment]
> Suggestion - you can decrease the spacing on top of filter component

I have made the changes, any other reviews? @anik31

**Comment by anik31** [comment]
> > Suggestion - you can decrease the spacing on top of filter component
> 
> I have made the changes, any other reviews? @anik31

Everything is good

**Review by ApurvaSawant11 — APPROVED** [review]
Looks good to me! Nice UI :)

**Review by Dev-AkshatGupta — APPROVED** [review]
Looks pretty well to me

**Comment by yash9263** [comment]
Looks good to me nice UI

**Review by yash9263 — APPROVED** [review]

**Pull request merged**
